SELECT EMPL_NUM, NAME, AGE, TITLE
FROM SALESREPS
WHERE AGE > 45
ORDER BY AGE DESC

SELECT DISTINCT MFR , PRODUCT 
FROM ORDERS
WHERE YEAR(ORDER_DATE) = 2008

SELECT TOP 1 WITH TIES REP, COUNT(*) AS ORDER_NUMBER
FROM ORDERS
WHERE YEAR(ORDER_DATE) = 2008
GROUP BY REP
ORDER BY ORDER_NUMBER DESC
