SELECT OFFICE, CITY, MGR
FROM OFFICES
WHERE SALES <= 350000.00 AND REGION = 'Eastern'

SELECT *
FROM ORDERS
WHERE YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
AND PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%'

SELECT MFR, COUNT(DISTINCT ORDER_NUM) AS ORDER_NUMBER
FROM ORDERS
WHERE YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
AND PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%'
GROUP BY MFR
ORDER BY SUM(AMOUNT) ASC;

SELECT TOP 1 WITH TIES MFR, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM ORDERS
WHERE YEAR(ORDER_DATE) NOT BETWEEN 2008 AND 2008
AND PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%'
GROUP BY MFR
ORDER BY SUM(AMOUNT) DESC;

SELECT TOP 1 WITH TIES REP_OFFICE, COUNT(*) AS NUMBER
FROM SALESREPS
WHERE AGE IN (29, 45, 48)
AND TITLE = 'Sales Rep'
GROUP BY REP_OFFICE
ORDER BY COUNT(*) DESC;