SELECT DISTINCT MFR
FROM ORDERS 
WHERE YEAR(ORDER_DATE) = 2008 
ORDER BY MFR ASC;

SELECT DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS Кількість_років,
COUNT(*) AS Кількість_працівників
FROM SALESREPS
GROUP BY DATEDIFF(YEAR, HIRE_DATE, GETDATE())
ORDER BY Кількість_працівників DESC;

SELECT TOP 1 WITH TIES YEAR(HIRE_DATE) AS Рік_найму, MONTH(HIRE_DATE) AS Місяць_найму, COUNT(*) AS Кількість_працівників
FROM SALESREPS
GROUP BY YEAR(HIRE_DATE), MONTH(HIRE_DATE)
ORDER BY Кількість_працівників DESC;

SELECT DATEPART(WEEKDAY, ORDER_DATE) AS Номер_дня_тижня, DATENAME(WEEKDAY, ORDER_DATE) AS Назва_дня_тижня, COUNT(DISTINCT ORDER_NUM) AS Загальна_кількість_замовлень,
SUM(AMOUNT) AS Загальна_сума_продаж,
SUM(QTY) AS Загальна_кількість_проданих_одиниць
FROM ORDERS
WHERE MONTH(ORDER_DATE) IN (12, 1, 2)
GROUP BY DATEPART(WEEKDAY, ORDER_DATE), DATENAME(WEEKDAY, ORDER_DATE)
ORDER BY Номер_дня_тижня;